"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$nodejs\
$time\
$cmd_duration\
$line_break\
$character"""

[time]
#disabled = false

[directory]
# truncate_to_repo = false
